---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Target: where our play will run and options it will run with
  hosts: control 
  gather_facts: false

  pre_tasks:
    - setup:
         filter: ansible_local
            # gather_subset: 'local'

  # Variable: variables that will apply to the play, on all target systems

  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test facts for subset distribution
      debug:
        msg: "{{ ansible_distribution }}"

    - name: Show Custom Fact 1
      debug:
        msg: "{{ ansible_local.getUname_a1 }}"

    - name: Show Custom Fact 2
      debug:
        msg: "{{ ansible_local.getUname_a2 }}"

# Three dots indicate the end of a YAML document
...
