---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list 
# of plays, with each play being a dictionary
-

  # Target: where our play will run and options it will run with
  hosts: linux
  become: true
  gather_facts: true

  # Variable: vvariables that will apply to the play, on all target systems
  vars:
    motd_ubuntu: "Welcome to CentOS 8.x and yeah....ANSIBLE UB\n"
    motd_centos: "Welcome to Ubuntu 20.04.1 LTS FOCAL FOSSA - ANSIBLE CENT\n"
  vars_prompt:
          name: username
          private: true
  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd_ubuntu }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "Ubuntu"

    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd_centos }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "CentOS"
    
    - name: debug message
      debug:
        msg: The hostvar ansible_host value for {{ ansible_hostname }} is {{ hostvars[ansible_hostname].ansible_host }}
      when: ansible_hostname != "ansible-controller"

    - name: debug message
      debug:
        msg: The username you entered is {{ username }}

  # Handlers: handlers that are executed as a notify key from a task
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed {{ username }}

  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
...
